// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzyLgljMM-NyLEVx9ivDczlgnbcC-gGeY',
    appId: '1:1020162499350:web:c7ad1ad4c8af213d9d2637',
    messagingSenderId: '1020162499350',
    projectId: 'cryptic-3d22c',
    authDomain: 'cryptic-3d22c.firebaseapp.com',
    databaseURL: 'https://cryptic-3d22c-default-rtdb.firebaseio.com',
    storageBucket: 'cryptic-3d22c.appspot.com',
    measurementId: 'G-6BQLBX44E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG6u4f2an8SqEtJ0TVu3UsgxQ9i1ej9LI',
    appId: '1:1020162499350:android:62333b33ae92f5ec9d2637',
    messagingSenderId: '1020162499350',
    projectId: 'cryptic-3d22c',
    databaseURL: 'https://cryptic-3d22c-default-rtdb.firebaseio.com',
    storageBucket: 'cryptic-3d22c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6U7S1yhwXdPAJt2tTMnGZWSPirzcvwj8',
    appId: '1:1020162499350:ios:88b6256f610f64539d2637',
    messagingSenderId: '1020162499350',
    projectId: 'cryptic-3d22c',
    databaseURL: 'https://cryptic-3d22c-default-rtdb.firebaseio.com',
    storageBucket: 'cryptic-3d22c.appspot.com',
    iosClientId: '1020162499350-b3e9k1d1qlghsju8jhq0pmljn13os7mm.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6U7S1yhwXdPAJt2tTMnGZWSPirzcvwj8',
    appId: '1:1020162499350:ios:88b6256f610f64539d2637',
    messagingSenderId: '1020162499350',
    projectId: 'cryptic-3d22c',
    databaseURL: 'https://cryptic-3d22c-default-rtdb.firebaseio.com',
    storageBucket: 'cryptic-3d22c.appspot.com',
    iosClientId: '1020162499350-b3e9k1d1qlghsju8jhq0pmljn13os7mm.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptic',
  );
}
